replicaCount: 1

image:
  repository: ghcr.io/gmelan/findart-backend
  tag: "86e67a253f29becad0f83e299a3c9662d5769805"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: findart-backend

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  internalHost: findart.internal
  externalHost: findart-api.jshyeon.com
  path: /
  pathType: Prefix

application:
  profile: prod

database:
  secretName: findart-db-secret
  urlKey: url
  usernameKey: username
  passwordKey: password

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: "1"
    memory: 1Gi

probes:
  startup:
    enabled: true
    failureThreshold: 30
    periodSeconds: 5

  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
